/*
* generated by Xtext
*/
package org.zhouxuan.example.myaml.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class AmlGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class AmlElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Aml");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsAbstractElementsParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//Aml hidden(WS, ML_COMMENT, SL_COMMENT):
		//	elements+=AbstractElements*;
		public ParserRule getRule() { return rule; }

		//elements+=AbstractElements*
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//AbstractElements
		public RuleCall getElementsAbstractElementsParserRuleCall_0() { return cElementsAbstractElementsParserRuleCall_0; }
	}

	public class AbstractElementsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "AbstractElements");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cEntityParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cPriceRuleParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSuperEntityParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMinMaxParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//AbstractElements:
		//	Entity | PriceRule | SuperEntity | MinMax;
		public ParserRule getRule() { return rule; }

		//Entity | PriceRule | SuperEntity | MinMax
		public Alternatives getAlternatives() { return cAlternatives; }

		//Entity
		public RuleCall getEntityParserRuleCall_0() { return cEntityParserRuleCall_0; }

		//PriceRule
		public RuleCall getPriceRuleParserRuleCall_1() { return cPriceRuleParserRuleCall_1; }

		//SuperEntity
		public RuleCall getSuperEntityParserRuleCall_2() { return cSuperEntityParserRuleCall_2; }

		//MinMax
		public RuleCall getMinMaxParserRuleCall_3() { return cMinMaxParserRuleCall_3; }
	}

	public class MinMaxElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MinMax");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTargetGroupFeatureAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTargetGroupFeatureTargetGroupFeatureParserRuleCall_2_0 = (RuleCall)cTargetGroupFeatureAssignment_2.eContents().get(0);
		private final Assignment cProductPuidsFeatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cProductPuidsFeatureProductPUIDFeatureParserRuleCall_3_0 = (RuleCall)cProductPuidsFeatureAssignment_3.eContents().get(0);
		private final Assignment cMaxFeatureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMaxFeatureMaxFeatureParserRuleCall_4_0 = (RuleCall)cMaxFeatureAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//MinMax:
		//	name=ID "{" targetGroupFeature=TargetGroupFeature productPuidsFeature=ProductPUIDFeature maxFeature=MaxFeature "}";
		public ParserRule getRule() { return rule; }

		//name=ID "{" targetGroupFeature=TargetGroupFeature productPuidsFeature=ProductPUIDFeature maxFeature=MaxFeature "}"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//targetGroupFeature=TargetGroupFeature
		public Assignment getTargetGroupFeatureAssignment_2() { return cTargetGroupFeatureAssignment_2; }

		//TargetGroupFeature
		public RuleCall getTargetGroupFeatureTargetGroupFeatureParserRuleCall_2_0() { return cTargetGroupFeatureTargetGroupFeatureParserRuleCall_2_0; }

		//productPuidsFeature=ProductPUIDFeature
		public Assignment getProductPuidsFeatureAssignment_3() { return cProductPuidsFeatureAssignment_3; }

		//ProductPUIDFeature
		public RuleCall getProductPuidsFeatureProductPUIDFeatureParserRuleCall_3_0() { return cProductPuidsFeatureProductPUIDFeatureParserRuleCall_3_0; }

		//maxFeature=MaxFeature
		public Assignment getMaxFeatureAssignment_4() { return cMaxFeatureAssignment_4; }

		//MaxFeature
		public RuleCall getMaxFeatureMaxFeatureParserRuleCall_4_0() { return cMaxFeatureMaxFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class MaxFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MaxFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameMaxKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//MaxFeature:
		//	name="Max" "=" value=INT;
		public ParserRule getRule() { return rule; }

		//name="Max" "=" value=INT
		public Group getGroup() { return cGroup; }

		//name="Max"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"Max"
		public Keyword getNameMaxKeyword_0_0() { return cNameMaxKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}

	public class ProductPUIDFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ProductPUIDFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameProductPUIDsKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValuesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValuesINTTerminalRuleCall_2_0 = (RuleCall)cValuesAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cValuesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cValuesINTTerminalRuleCall_3_1_0 = (RuleCall)cValuesAssignment_3_1.eContents().get(0);
		
		//ProductPUIDFeature:
		//	name="ProductPUIDs" "=" values+=INT ("," values+=INT)*;
		public ParserRule getRule() { return rule; }

		//name="ProductPUIDs" "=" values+=INT ("," values+=INT)*
		public Group getGroup() { return cGroup; }

		//name="ProductPUIDs"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"ProductPUIDs"
		public Keyword getNameProductPUIDsKeyword_0_0() { return cNameProductPUIDsKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//values+=INT
		public Assignment getValuesAssignment_2() { return cValuesAssignment_2; }

		//INT
		public RuleCall getValuesINTTerminalRuleCall_2_0() { return cValuesINTTerminalRuleCall_2_0; }

		//("," values+=INT)*
		public Group getGroup_3() { return cGroup_3; }

		//","
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }

		//values+=INT
		public Assignment getValuesAssignment_3_1() { return cValuesAssignment_3_1; }

		//INT
		public RuleCall getValuesINTTerminalRuleCall_3_1_0() { return cValuesINTTerminalRuleCall_3_1_0; }
	}

	public class TargetGroupFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TargetGroupFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameTargetGroupKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueIDTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//TargetGroupFeature:
		//	name="TargetGroup" "=" value=ID;
		public ParserRule getRule() { return rule; }

		//name="TargetGroup" "=" value=ID
		public Group getGroup() { return cGroup; }

		//name="TargetGroup"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"TargetGroup"
		public Keyword getNameTargetGroupKeyword_0_0() { return cNameTargetGroupKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=ID
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_2_0() { return cValueIDTerminalRuleCall_2_0; }
	}

	public class DriveElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Drive");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTypeFeatureAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTypeFeatureTypeFeatureParserRuleCall_2_0 = (RuleCall)cTypeFeatureAssignment_2.eContents().get(0);
		private final Assignment cSizeFeatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSizeFeatureSizeFeatureParserRuleCall_3_0 = (RuleCall)cSizeFeatureAssignment_3.eContents().get(0);
		private final Assignment cSpeedFeatureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cSpeedFeatureSpeedFeatureParserRuleCall_4_0 = (RuleCall)cSpeedFeatureAssignment_4.eContents().get(0);
		private final Assignment cFormFeatureAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cFormFeatureFormFeatureParserRuleCall_5_0 = (RuleCall)cFormFeatureAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Drive:
		//	name=ID "{" typeFeature=TypeFeature sizeFeature=SizeFeature speedFeature=SpeedFeature formFeature=FormFeature "}";
		public ParserRule getRule() { return rule; }

		//name=ID "{" typeFeature=TypeFeature sizeFeature=SizeFeature speedFeature=SpeedFeature formFeature=FormFeature "}"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//typeFeature=TypeFeature
		public Assignment getTypeFeatureAssignment_2() { return cTypeFeatureAssignment_2; }

		//TypeFeature
		public RuleCall getTypeFeatureTypeFeatureParserRuleCall_2_0() { return cTypeFeatureTypeFeatureParserRuleCall_2_0; }

		//sizeFeature=SizeFeature
		public Assignment getSizeFeatureAssignment_3() { return cSizeFeatureAssignment_3; }

		//SizeFeature
		public RuleCall getSizeFeatureSizeFeatureParserRuleCall_3_0() { return cSizeFeatureSizeFeatureParserRuleCall_3_0; }

		//speedFeature=SpeedFeature
		public Assignment getSpeedFeatureAssignment_4() { return cSpeedFeatureAssignment_4; }

		//SpeedFeature
		public RuleCall getSpeedFeatureSpeedFeatureParserRuleCall_4_0() { return cSpeedFeatureSpeedFeatureParserRuleCall_4_0; }

		//formFeature=FormFeature
		public Assignment getFormFeatureAssignment_5() { return cFormFeatureAssignment_5; }

		//FormFeature
		public RuleCall getFormFeatureFormFeatureParserRuleCall_5_0() { return cFormFeatureFormFeatureParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class FormFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "FormFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameFormFactorKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//FormFeature:
		//	name="formFactor" "=" value=INT;
		public ParserRule getRule() { return rule; }

		//name="formFactor" "=" value=INT
		public Group getGroup() { return cGroup; }

		//name="formFactor"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"formFactor"
		public Keyword getNameFormFactorKeyword_0_0() { return cNameFormFactorKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}

	public class SpeedFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SpeedFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameSpeedKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueDOUBLEParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//SpeedFeature:
		//	name="speed" "=" value=DOUBLE;
		public ParserRule getRule() { return rule; }

		//name="speed" "=" value=DOUBLE
		public Group getGroup() { return cGroup; }

		//name="speed"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"speed"
		public Keyword getNameSpeedKeyword_0_0() { return cNameSpeedKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=DOUBLE
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//DOUBLE
		public RuleCall getValueDOUBLEParserRuleCall_2_0() { return cValueDOUBLEParserRuleCall_2_0; }
	}

	public class SizeFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SizeFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameSizeKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueINTTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//SizeFeature:
		//	name="size" "=" value=INT;
		public ParserRule getRule() { return rule; }

		//name="size" "=" value=INT
		public Group getGroup() { return cGroup; }

		//name="size"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"size"
		public Keyword getNameSizeKeyword_0_0() { return cNameSizeKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=INT
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//INT
		public RuleCall getValueINTTerminalRuleCall_2_0() { return cValueINTTerminalRuleCall_2_0; }
	}

	public class TypeFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TypeFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameTypeKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueSTRINGTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		
		//TypeFeature:
		//	name="type" "=" value=STRING;
		public ParserRule getRule() { return rule; }

		//name="type" "=" value=STRING
		public Group getGroup() { return cGroup; }

		//name="type"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"type"
		public Keyword getNameTypeKeyword_0_0() { return cNameTypeKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=STRING
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_2_0() { return cValueSTRINGTerminalRuleCall_2_0; }
	}

	public class CableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColorFeatureAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColorFeatureColorFeatureParserRuleCall_2_0 = (RuleCall)cColorFeatureAssignment_2.eContents().get(0);
		private final Assignment cNetworkFeatureAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNetworkFeatureNetWorkFeatureParserRuleCall_3_0 = (RuleCall)cNetworkFeatureAssignment_3.eContents().get(0);
		private final Assignment cLengthFeatureAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLengthFeatureLengthFeatureParserRuleCall_4_0 = (RuleCall)cLengthFeatureAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Cable:
		//	name=ID "{" colorFeature=ColorFeature networkFeature=NetWorkFeature lengthFeature=LengthFeature "}";
		public ParserRule getRule() { return rule; }

		//name=ID "{" colorFeature=ColorFeature networkFeature=NetWorkFeature lengthFeature=LengthFeature "}"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//colorFeature=ColorFeature
		public Assignment getColorFeatureAssignment_2() { return cColorFeatureAssignment_2; }

		//ColorFeature
		public RuleCall getColorFeatureColorFeatureParserRuleCall_2_0() { return cColorFeatureColorFeatureParserRuleCall_2_0; }

		//networkFeature=NetWorkFeature
		public Assignment getNetworkFeatureAssignment_3() { return cNetworkFeatureAssignment_3; }

		//NetWorkFeature
		public RuleCall getNetworkFeatureNetWorkFeatureParserRuleCall_3_0() { return cNetworkFeatureNetWorkFeatureParserRuleCall_3_0; }

		//lengthFeature=LengthFeature
		public Assignment getLengthFeatureAssignment_4() { return cLengthFeatureAssignment_4; }

		//LengthFeature
		public RuleCall getLengthFeatureLengthFeatureParserRuleCall_4_0() { return cLengthFeatureLengthFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class PriceRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PriceRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRuleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeMinMaxCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeMinMaxQualifiedNameParserRuleCall_2_1_0_1 = (RuleCall)cSuperTypeMinMaxCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeaturesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeaturesFeatureParserRuleCall_4_0 = (RuleCall)cFeaturesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//PriceRule:
		//	"rule" name=ID ("extends" superType=[MinMax|QualifiedName])? "{" features+=Feature* "}";
		public ParserRule getRule() { return rule; }

		//"rule" name=ID ("extends" superType=[MinMax|QualifiedName])? "{" features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//"rule"
		public Keyword getRuleKeyword_0() { return cRuleKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[MinMax|QualifiedName])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[MinMax|QualifiedName]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[MinMax|QualifiedName]
		public CrossReference getSuperTypeMinMaxCrossReference_2_1_0() { return cSuperTypeMinMaxCrossReference_2_1_0; }

		//QualifiedName
		public RuleCall getSuperTypeMinMaxQualifiedNameParserRuleCall_2_1_0_1() { return cSuperTypeMinMaxQualifiedNameParserRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_4() { return cFeaturesAssignment_4; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_4_0() { return cFeaturesFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Entity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPuidKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cExtendsKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuperTypeAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final CrossReference cSuperTypeSuperEntityCrossReference_2_1_0 = (CrossReference)cSuperTypeAssignment_2_1.eContents().get(0);
		private final RuleCall cSuperTypeSuperEntityQualifiedNameParserRuleCall_2_1_0_1 = (RuleCall)cSuperTypeSuperEntityCrossReference_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cFeaturesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cFeaturesFeatureParserRuleCall_4_0 = (RuleCall)cFeaturesAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Entity:
		//	"puid" name=ID ("extends" superType=[SuperEntity|QualifiedName])? "{" features+=Feature* "}";
		public ParserRule getRule() { return rule; }

		//"puid" name=ID ("extends" superType=[SuperEntity|QualifiedName])? "{" features+=Feature* "}"
		public Group getGroup() { return cGroup; }

		//"puid"
		public Keyword getPuidKeyword_0() { return cPuidKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//("extends" superType=[SuperEntity|QualifiedName])?
		public Group getGroup_2() { return cGroup_2; }

		//"extends"
		public Keyword getExtendsKeyword_2_0() { return cExtendsKeyword_2_0; }

		//superType=[SuperEntity|QualifiedName]
		public Assignment getSuperTypeAssignment_2_1() { return cSuperTypeAssignment_2_1; }

		//[SuperEntity|QualifiedName]
		public CrossReference getSuperTypeSuperEntityCrossReference_2_1_0() { return cSuperTypeSuperEntityCrossReference_2_1_0; }

		//QualifiedName
		public RuleCall getSuperTypeSuperEntityQualifiedNameParserRuleCall_2_1_0_1() { return cSuperTypeSuperEntityQualifiedNameParserRuleCall_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//features+=Feature*
		public Assignment getFeaturesAssignment_4() { return cFeaturesAssignment_4; }

		//Feature
		public RuleCall getFeaturesFeatureParserRuleCall_4_0() { return cFeaturesFeatureParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}

	public class FeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Feature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cNameIDTerminalRuleCall_0_0 = (RuleCall)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueIDTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//Feature:
		//	name=ID "=" value=ID ";";
		public ParserRule getRule() { return rule; }

		//name=ID "=" value=ID ";"
		public Group getGroup() { return cGroup; }

		//name=ID
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_0_0() { return cNameIDTerminalRuleCall_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=ID
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_2_0() { return cValueIDTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class LengthFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LengthFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameLengthKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueDOUBLEParserRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//LengthFeature:
		//	name="length" "=" value=DOUBLE ";";
		public ParserRule getRule() { return rule; }

		//name="length" "=" value=DOUBLE ";"
		public Group getGroup() { return cGroup; }

		//name="length"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"length"
		public Keyword getNameLengthKeyword_0_0() { return cNameLengthKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=DOUBLE
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//DOUBLE
		public RuleCall getValueDOUBLEParserRuleCall_2_0() { return cValueDOUBLEParserRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class DOUBLEElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DOUBLE");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//DOUBLE returns ecore::EDouble:
		//	INT "." INT;
		public ParserRule getRule() { return rule; }

		//INT "." INT
		public Group getGroup() { return cGroup; }

		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }

		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}

	public class NetWorkFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NetWorkFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameNetworkKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueIDTerminalRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//NetWorkFeature:
		//	name="network" "=" value=ID ";";
		public ParserRule getRule() { return rule; }

		//name="network" "=" value=ID ";"
		public Group getGroup() { return cGroup; }

		//name="network"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"network"
		public Keyword getNameNetworkKeyword_0_0() { return cNameNetworkKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=ID
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_2_0() { return cValueIDTerminalRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class ColorFeatureElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ColorFeature");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cNameAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cNameColorKeyword_0_0 = (Keyword)cNameAssignment_0.eContents().get(0);
		private final Keyword cEqualsSignKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cValueAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cValueColorEnumRuleCall_2_0 = (RuleCall)cValueAssignment_2.eContents().get(0);
		private final Keyword cSemicolonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ColorFeature:
		//	name="color" "=" value=Color ";";
		public ParserRule getRule() { return rule; }

		//name="color" "=" value=Color ";"
		public Group getGroup() { return cGroup; }

		//name="color"
		public Assignment getNameAssignment_0() { return cNameAssignment_0; }

		//"color"
		public Keyword getNameColorKeyword_0_0() { return cNameColorKeyword_0_0; }

		//"="
		public Keyword getEqualsSignKeyword_1() { return cEqualsSignKeyword_1; }

		//value=Color
		public Assignment getValueAssignment_2() { return cValueAssignment_2; }

		//Color
		public RuleCall getValueColorEnumRuleCall_2_0() { return cValueColorEnumRuleCall_2_0; }

		//";"
		public Keyword getSemicolonKeyword_3() { return cSemicolonKeyword_3; }
	}

	public class SuperEntityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SuperEntity");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCableParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDriveParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//SuperEntity:
		//	Cable | Drive;
		public ParserRule getRule() { return rule; }

		//Cable | Drive
		public Alternatives getAlternatives() { return cAlternatives; }

		//Cable
		public RuleCall getCableParserRuleCall_0() { return cCableParserRuleCall_0; }

		//Drive
		public RuleCall getDriveParserRuleCall_1() { return cDriveParserRuleCall_1; }
	}
	
	
	public class ColorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Color");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cRedEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cRedRedKeyword_0_0 = (Keyword)cRedEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cBlackEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cBlackBlackKeyword_1_0 = (Keyword)cBlackEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cWhiteEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cWhiteWhiteKeyword_2_0 = (Keyword)cWhiteEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGreyEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGreyGreyKeyword_3_0 = (Keyword)cGreyEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGreenEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGreenGreenKeyword_4_0 = (Keyword)cGreenEnumLiteralDeclaration_4.eContents().get(0);
		
		//enum Color:
		//	Red | Black | White | Grey | Green;
		public EnumRule getRule() { return rule; }

		//Red | Black | White | Grey | Green
		public Alternatives getAlternatives() { return cAlternatives; }

		//Red
		public EnumLiteralDeclaration getRedEnumLiteralDeclaration_0() { return cRedEnumLiteralDeclaration_0; }

		//"Red"
		public Keyword getRedRedKeyword_0_0() { return cRedRedKeyword_0_0; }

		//Black
		public EnumLiteralDeclaration getBlackEnumLiteralDeclaration_1() { return cBlackEnumLiteralDeclaration_1; }

		//"Black"
		public Keyword getBlackBlackKeyword_1_0() { return cBlackBlackKeyword_1_0; }

		//White
		public EnumLiteralDeclaration getWhiteEnumLiteralDeclaration_2() { return cWhiteEnumLiteralDeclaration_2; }

		//"White"
		public Keyword getWhiteWhiteKeyword_2_0() { return cWhiteWhiteKeyword_2_0; }

		//Grey
		public EnumLiteralDeclaration getGreyEnumLiteralDeclaration_3() { return cGreyEnumLiteralDeclaration_3; }

		//"Grey"
		public Keyword getGreyGreyKeyword_3_0() { return cGreyGreyKeyword_3_0; }

		//Green
		public EnumLiteralDeclaration getGreenEnumLiteralDeclaration_4() { return cGreenEnumLiteralDeclaration_4; }

		//"Green"
		public Keyword getGreenGreenKeyword_4_0() { return cGreenGreenKeyword_4_0; }
	}
	
	private AmlElements pAml;
	private AbstractElementsElements pAbstractElements;
	private MinMaxElements pMinMax;
	private MaxFeatureElements pMaxFeature;
	private ProductPUIDFeatureElements pProductPUIDFeature;
	private TargetGroupFeatureElements pTargetGroupFeature;
	private DriveElements pDrive;
	private FormFeatureElements pFormFeature;
	private SpeedFeatureElements pSpeedFeature;
	private SizeFeatureElements pSizeFeature;
	private TypeFeatureElements pTypeFeature;
	private CableElements pCable;
	private PriceRuleElements pPriceRule;
	private EntityElements pEntity;
	private QualifiedNameElements pQualifiedName;
	private ColorElements unknownRuleColor;
	private FeatureElements pFeature;
	private LengthFeatureElements pLengthFeature;
	private DOUBLEElements pDOUBLE;
	private NetWorkFeatureElements pNetWorkFeature;
	private ColorFeatureElements pColorFeature;
	private SuperEntityElements pSuperEntity;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public AmlGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.zhouxuan.example.myaml.Aml".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Aml hidden(WS, ML_COMMENT, SL_COMMENT):
	//	elements+=AbstractElements*;
	public AmlElements getAmlAccess() {
		return (pAml != null) ? pAml : (pAml = new AmlElements());
	}
	
	public ParserRule getAmlRule() {
		return getAmlAccess().getRule();
	}

	//AbstractElements:
	//	Entity | PriceRule | SuperEntity | MinMax;
	public AbstractElementsElements getAbstractElementsAccess() {
		return (pAbstractElements != null) ? pAbstractElements : (pAbstractElements = new AbstractElementsElements());
	}
	
	public ParserRule getAbstractElementsRule() {
		return getAbstractElementsAccess().getRule();
	}

	//MinMax:
	//	name=ID "{" targetGroupFeature=TargetGroupFeature productPuidsFeature=ProductPUIDFeature maxFeature=MaxFeature "}";
	public MinMaxElements getMinMaxAccess() {
		return (pMinMax != null) ? pMinMax : (pMinMax = new MinMaxElements());
	}
	
	public ParserRule getMinMaxRule() {
		return getMinMaxAccess().getRule();
	}

	//MaxFeature:
	//	name="Max" "=" value=INT;
	public MaxFeatureElements getMaxFeatureAccess() {
		return (pMaxFeature != null) ? pMaxFeature : (pMaxFeature = new MaxFeatureElements());
	}
	
	public ParserRule getMaxFeatureRule() {
		return getMaxFeatureAccess().getRule();
	}

	//ProductPUIDFeature:
	//	name="ProductPUIDs" "=" values+=INT ("," values+=INT)*;
	public ProductPUIDFeatureElements getProductPUIDFeatureAccess() {
		return (pProductPUIDFeature != null) ? pProductPUIDFeature : (pProductPUIDFeature = new ProductPUIDFeatureElements());
	}
	
	public ParserRule getProductPUIDFeatureRule() {
		return getProductPUIDFeatureAccess().getRule();
	}

	//TargetGroupFeature:
	//	name="TargetGroup" "=" value=ID;
	public TargetGroupFeatureElements getTargetGroupFeatureAccess() {
		return (pTargetGroupFeature != null) ? pTargetGroupFeature : (pTargetGroupFeature = new TargetGroupFeatureElements());
	}
	
	public ParserRule getTargetGroupFeatureRule() {
		return getTargetGroupFeatureAccess().getRule();
	}

	//Drive:
	//	name=ID "{" typeFeature=TypeFeature sizeFeature=SizeFeature speedFeature=SpeedFeature formFeature=FormFeature "}";
	public DriveElements getDriveAccess() {
		return (pDrive != null) ? pDrive : (pDrive = new DriveElements());
	}
	
	public ParserRule getDriveRule() {
		return getDriveAccess().getRule();
	}

	//FormFeature:
	//	name="formFactor" "=" value=INT;
	public FormFeatureElements getFormFeatureAccess() {
		return (pFormFeature != null) ? pFormFeature : (pFormFeature = new FormFeatureElements());
	}
	
	public ParserRule getFormFeatureRule() {
		return getFormFeatureAccess().getRule();
	}

	//SpeedFeature:
	//	name="speed" "=" value=DOUBLE;
	public SpeedFeatureElements getSpeedFeatureAccess() {
		return (pSpeedFeature != null) ? pSpeedFeature : (pSpeedFeature = new SpeedFeatureElements());
	}
	
	public ParserRule getSpeedFeatureRule() {
		return getSpeedFeatureAccess().getRule();
	}

	//SizeFeature:
	//	name="size" "=" value=INT;
	public SizeFeatureElements getSizeFeatureAccess() {
		return (pSizeFeature != null) ? pSizeFeature : (pSizeFeature = new SizeFeatureElements());
	}
	
	public ParserRule getSizeFeatureRule() {
		return getSizeFeatureAccess().getRule();
	}

	//TypeFeature:
	//	name="type" "=" value=STRING;
	public TypeFeatureElements getTypeFeatureAccess() {
		return (pTypeFeature != null) ? pTypeFeature : (pTypeFeature = new TypeFeatureElements());
	}
	
	public ParserRule getTypeFeatureRule() {
		return getTypeFeatureAccess().getRule();
	}

	//Cable:
	//	name=ID "{" colorFeature=ColorFeature networkFeature=NetWorkFeature lengthFeature=LengthFeature "}";
	public CableElements getCableAccess() {
		return (pCable != null) ? pCable : (pCable = new CableElements());
	}
	
	public ParserRule getCableRule() {
		return getCableAccess().getRule();
	}

	//PriceRule:
	//	"rule" name=ID ("extends" superType=[MinMax|QualifiedName])? "{" features+=Feature* "}";
	public PriceRuleElements getPriceRuleAccess() {
		return (pPriceRule != null) ? pPriceRule : (pPriceRule = new PriceRuleElements());
	}
	
	public ParserRule getPriceRuleRule() {
		return getPriceRuleAccess().getRule();
	}

	//Entity:
	//	"puid" name=ID ("extends" superType=[SuperEntity|QualifiedName])? "{" features+=Feature* "}";
	public EntityElements getEntityAccess() {
		return (pEntity != null) ? pEntity : (pEntity = new EntityElements());
	}
	
	public ParserRule getEntityRule() {
		return getEntityAccess().getRule();
	}

	//QualifiedName:
	//	ID ("." ID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//enum Color:
	//	Red | Black | White | Grey | Green;
	public ColorElements getColorAccess() {
		return (unknownRuleColor != null) ? unknownRuleColor : (unknownRuleColor = new ColorElements());
	}
	
	public EnumRule getColorRule() {
		return getColorAccess().getRule();
	}

	//Feature:
	//	name=ID "=" value=ID ";";
	public FeatureElements getFeatureAccess() {
		return (pFeature != null) ? pFeature : (pFeature = new FeatureElements());
	}
	
	public ParserRule getFeatureRule() {
		return getFeatureAccess().getRule();
	}

	//LengthFeature:
	//	name="length" "=" value=DOUBLE ";";
	public LengthFeatureElements getLengthFeatureAccess() {
		return (pLengthFeature != null) ? pLengthFeature : (pLengthFeature = new LengthFeatureElements());
	}
	
	public ParserRule getLengthFeatureRule() {
		return getLengthFeatureAccess().getRule();
	}

	//DOUBLE returns ecore::EDouble:
	//	INT "." INT;
	public DOUBLEElements getDOUBLEAccess() {
		return (pDOUBLE != null) ? pDOUBLE : (pDOUBLE = new DOUBLEElements());
	}
	
	public ParserRule getDOUBLERule() {
		return getDOUBLEAccess().getRule();
	}

	//NetWorkFeature:
	//	name="network" "=" value=ID ";";
	public NetWorkFeatureElements getNetWorkFeatureAccess() {
		return (pNetWorkFeature != null) ? pNetWorkFeature : (pNetWorkFeature = new NetWorkFeatureElements());
	}
	
	public ParserRule getNetWorkFeatureRule() {
		return getNetWorkFeatureAccess().getRule();
	}

	//ColorFeature:
	//	name="color" "=" value=Color ";";
	public ColorFeatureElements getColorFeatureAccess() {
		return (pColorFeature != null) ? pColorFeature : (pColorFeature = new ColorFeatureElements());
	}
	
	public ParserRule getColorFeatureRule() {
		return getColorFeatureAccess().getRule();
	}

	//SuperEntity:
	//	Cable | Drive;
	public SuperEntityElements getSuperEntityAccess() {
		return (pSuperEntity != null) ? pSuperEntity : (pSuperEntity = new SuperEntityElements());
	}
	
	public ParserRule getSuperEntityRule() {
		return getSuperEntityAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
