/**
 * generated by Xtext
 */
package org.zhouxuan.example.myaml.validation;

import org.zhouxuan.example.myaml.validation.AbstractAmlValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class AmlValidator extends AbstractAmlValidator {
}
