/*
* generated by Xtext
*/
package org.zhouxuan.example.myaml.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AmlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("org/zhouxuan/example/myaml/parser/antlr/internal/InternalAml.tokens");
	}
}
