/*
* generated by Xtext
*/
package org.zhouxuan.example.myaml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.zhouxuan.example.myaml.services.AmlGrammarAccess;

public class AmlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AmlGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.zhouxuan.example.myaml.parser.antlr.internal.InternalAmlParser createParser(XtextTokenStream stream) {
		return new org.zhouxuan.example.myaml.parser.antlr.internal.InternalAmlParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Aml";
	}
	
	public AmlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AmlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
