/*
* generated by Xtext
*/
package org.zhouxuan.example.myaml;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AmlUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.zhouxuan.example.myaml.ui.internal.AmlActivator.getInstance().getInjector("org.zhouxuan.example.myaml.Aml");
	}
	
}
