/*
 * generated by Xtext
 */
package org.zhouxuan.example.myaml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractAmlValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.zhouxuan.example.myaml.aml.AmlPackage.eINSTANCE);
		return result;
	}
}
