/**
 * generated by Xtext
 */
package org.zhouxuan.example.myaml.ui.contentassist;

import org.zhouxuan.example.myaml.ui.contentassist.AbstractAmlProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class AmlProposalProvider extends AbstractAmlProposalProvider {
}
