/*
 * generated by Xtext
 */
package org.zhouxuan.example.myaml.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.zhouxuan.example.myaml.ui.internal.AmlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AmlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AmlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AmlActivator.getInstance().getInjector(AmlActivator.ORG_ZHOUXUAN_EXAMPLE_MYAML_AML);
	}
	
}
