/*
 * generated by Xtext
 */
package org.zhouxuan.example.myaml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AmlUiModule extends org.zhouxuan.example.myaml.ui.AbstractAmlUiModule {
	public AmlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
