/*
 * generated by Xtext
 */
package org.zhouxuan.example.myaml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AmlRuntimeModule extends org.zhouxuan.example.myaml.AbstractAmlRuntimeModule {

}
